name: Backend Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        java-version: "21"
        distribution: "adopt"
    - run: cd backend/
    - run: mvn -B test
      env:
        QUARKUS_MONGODB_CONNECTION_STRING: mongodb://localhost:27017